### ISSUE TITLE
Outdated exporter in app.zip file

### ISSUE THREAD

**Issue by genmielec** [drifted-in/genopro-webapp-exporter#1]
It doesn't generate a page for me.
I used: http://drifted.in/other/genopro-webapp-exporter/app.zip

I named the files and folders as well as yours.
I tried on drive C and on drive D.

Page not generated. There are no new files in the directory. I only have the message:

`D:\>java -jar D:\genopro-webapp-exporter.jar -in:"D:\family-tree.gno" -out:"D:\family-tree" -mode:static
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at in.drifted.tools.genopro.DataParser.getBoundaryRect(DataParser.java:513)
        at in.drifted.tools.genopro.DataParser.getGenoMapMap(DataParser.java:91)
        at in.drifted.tools.genopro.DataUtil.getGenoMapDataList(DataUtil.java:47)
        at in.drifted.tools.genopro.webapp.App.main(App.java:126)

D:\>java -jar genopro-webapp-exporter.jar -in:"D:\family-tree.gno" -out:"D:\family-tree" -relativeAppUrl:/family-tree
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at in.drifted.tools.genopro.DataParser.getBoundaryRect(DataParser.java:513)
        at in.drifted.tools.genopro.DataParser.getGenoMapMap(DataParser.java:91)
        at in.drifted.tools.genopro.DataUtil.getGenoMapDataList(DataUtil.java:47)
        at in.drifted.tools.genopro.webapp.App.main(App.java:126)`

**Comment by jan-tosovsky-cz** [comment]
@genmielec Can you share (or send directly to my email address shown on my profile) your GNO file (reduced/anonymized or its subset)? It looks yours has unexpected internal structure so my parser fails.

**Comment by genmielec** [comment]
I sent an email.

Maybe the mistake is on my side. I tried on a smaller file but the problem is the same.

Send me your * .gno file - I'll try if it works.

Java version below:

D

> : \> java -showversion
> java version "1.8.0_241"
> Java (TM) SE Runtime Environment (build 1.8.0_241-b07)
> Java HotSpot (TM) Client VM (build 25.241-b07, mixed mode)

**Comment by jan-tosovsky-cz** [comment]
Thanks for the sample file. This issue seems to be fixed in meantime https://github.com/drifted-in/genopro-core/commit/1926e2f744aa40df1b27c40d81f4d7d7d3f78731 
The problem here is the link to outdated binary. I've just replaced the `app.zip` with the most recent version.

**Comment by genmielec** [comment]
Unfortunately, the app.zip file is still old and has a file from October 13, 2018. Can you upload the new version again? I can't compile the file.

However, I read drifted-in / genopro-core @ 1926e2f and from what I saw, the problem was that there were empty genomaps in the GNO file. I removed them from my tree. When trying to generate (on the old app.zip file) I have this message (much shorter than before):

> D:\>java -jar D:\genopro-webapp-exporter.jar -in:"D:\family-tree.gno" -out:"D:\family-tree" -mode:static
> Exception in thread "main" java.lang.NullPointerException
>         at in.drifted.tools.genopro.DataUtil.getGenoMapDataList(DataUtil.java:58)
>         at in.drifted.tools.genopro.webapp.App.main(App.java:126)
> 
> D:\>java -jar genopro-webapp-exporter.jar -in:"D:\family-tree.gno" -out:"D:\family-tree" -relativeAppUrl:/family-tree
> Exception in thread "main" java.lang.NullPointerException
>         at in.drifted.tools.genopro.DataUtil.getGenoMapDataList(DataUtil.java:58)
>         at in.drifted.tools.genopro.webapp.App.main(App.java:126)

**Comment by jan-tosovsky-cz** [comment]
It works for me. Can you clear your browser cache? Or try downloading using different browser? That old version have several other bugs which were eliminated in meantime.

**Comment by genmielec** [comment]
I already have the current file.
It almost works ...

Page is being generated but is empty.

I have this message:

> D:\>java -jar D:\genopro-webapp-exporter.jar -in:"D:\family-tree.gno" -out:"D:\family-tree" -mode:static
> 
> D:\>java -jar genopro-webapp-exporter.jar -in:"D:\family-tree.gno" -out:"D:\family-tree" -relativeAppUrl:/family-tree
> Exception in thread "main" java.util.NoSuchElementException
>         at java.util.ArrayList$Itr.next(Unknown Source)
>         at in.drifted.tools.genopro.webapp.WebAppExporter.generateMainHtml(WebAppExporter.java:96)
>         at in.drifted.tools.genopro.webapp.WebAppExporter.export(WebAppExporter.java:63)
>         at in.drifted.tools.genopro.webapp.App.main(App.java:135)

**Comment by jan-tosovsky-cz** [comment]
Can you create separate issue for this? Apparently there is no GenoMap to export, but there is no check for this in my code. Please read carefully Data Preparation section. All GenoMaps to Export should have Report Title set, otherwise they are ignored.
